### ISSUE TITLE
Validation for disco outputs failing

### ISSUE THREAD

**Issue by tanushree04** [urbanopt/urbanopt-reporting-gem#125]
bundle exec uo process --disco -s `scenario file` -f  `feature file` is failing

https://github.com/urbanopt/urbanopt-reporting-gem/blob/46f24fd5459b4b26ce0de883cec3b118d92d12fe/lib/urbanopt/reporting/default_reports/scenario_power_distribution_cost.rb#L105

Is failing with this message: 

urbanopt-reporting-gem/lib/urbanopt/reporting/default_reports/scenario_power_distribution_cost.rb:105:in `to_hash': scenario_power_distribution_cost properties does not match schema: ["The property '#/outputs' of type object did not match all of the required schemas. The schema specific errors were:\\n\\n- allOf #0:\\n    - The property '#/outputs' did not contain a required property of 'jobs'\\n    - The property '#/outputs' did not contain a required property of 'log_file'"] (RuntimeError)

**Comment by vtnate** [comment]
Closed by #124
