### ISSUE TITLE
Aggregate EUI's in Scenario Report

### ISSUE THREAD

**Issue by vtnate** [urbanopt/urbanopt-reporting-gem#40]
The post-processor doesn't appear to aggregate the EUI's in default_scenario_report.json[scenario_report][reporting_periods].

**Comment by rawadelkontar** [comment]
@vtnate
Yes, I only reported EUI in the feature reports. EUI is usually used to compare the energy intensity across buildings / building types. We can add the aggregated EUI number but I am not sure it is that important.
