### ISSUE TITLE
EnergyPlus changed output fuel names in version 9.4

### ISSUE THREAD

**Issue by vtnate** [urbanopt/urbanopt-reporting-gem#64]
For instance, `Gas` is now `NaturalGas`. We don't want to lose that energy use.

**Comment by joseph-robertson** [comment]
To be clear, EnergyPlus was changed. And not only `Gas` to `NaturalGas`, but `FuelOil#1` to `FuelOilNo1` and `FuelOil#2` to `FuelOilNo2`. Also, `Additional Fuels` doesn't appear to populate in the sql out file anymore.

**Comment by vtnate** [comment]
Thanks Joe. I changed the name of the issue to correct that.
